/*
 * NabooApi V1
 *
 * Here you have the first version of the naboo api to create checkout automatically
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeleteTransactionRequest {
    #[serde(rename = "order_id")]
    pub order_id: String,
}

impl DeleteTransactionRequest {
    pub fn new(order_id: String) -> DeleteTransactionRequest {
        DeleteTransactionRequest {
            order_id,
        }
    }
}

