/*
 * NabooApi V1
 *
 * Here you have the first version of the naboo api to create checkout automatically
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeleteTransactionResponse {
    #[serde(rename = "order_id")]
    pub order_id: String,
    #[serde(rename = "message")]
    pub message: String,
}

impl DeleteTransactionResponse {
    pub fn new(order_id: String, message: String) -> DeleteTransactionResponse {
        DeleteTransactionResponse {
            order_id,
            message,
        }
    }
}

