/*
 * NabooApi V1
 *
 * Here you have the first version of the naboo api to create checkout automatically
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetAccountResponse {
    #[serde(rename = "account_number")]
    pub account_number: String,
    #[serde(rename = "balance")]
    pub balance: f64,
    #[serde(rename = "account_is_activate")]
    pub account_is_activate: bool,
    #[serde(rename = "method_of_payment")]
    pub method_of_payment: models::Wallet,
    #[serde(rename = "loyalty_credit")]
    pub loyalty_credit: i32,
}

impl GetAccountResponse {
    pub fn new(account_number: String, balance: f64, account_is_activate: bool, method_of_payment: models::Wallet, loyalty_credit: i32) -> GetAccountResponse {
        GetAccountResponse {
            account_number,
            balance,
            account_is_activate,
            method_of_payment,
            loyalty_credit,
        }
    }
}

