/*
 * NabooApi V1
 *
 * Here you have the first version of the naboo api to create checkout automatically
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProductModel {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "category")]
    pub category: String,
    #[serde(rename = "amount")]
    pub amount: i32,
    #[serde(rename = "quantity")]
    pub quantity: i32,
    #[serde(rename = "description")]
    pub description: String,
}

impl ProductModel {
    pub fn new(name: String, category: String, amount: i32, quantity: i32, description: String) -> ProductModel {
        ProductModel {
            name,
            category,
            amount,
            quantity,
            description,
        }
    }
}

