/*
 * NabooApi V1
 *
 * Here you have the first version of the naboo api to create checkout automatically
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Wallet {
    #[serde(rename = "WAVE")]
    Wave,
    #[serde(rename = "ORANGE_MONEY")]
    OrangeMoney,
    #[serde(rename = "FREE_MONEY")]
    FreeMoney,

}

impl std::fmt::Display for Wallet {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Wave => write!(f, "WAVE"),
            Self::OrangeMoney => write!(f, "ORANGE_MONEY"),
            Self::FreeMoney => write!(f, "FREE_MONEY"),
        }
    }
}

impl Default for Wallet {
    fn default() -> Wallet {
        Self::Wave
    }
}

